[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "https://api-hjtd337cca-uc.a.run.app/api/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "playwright-core"]

[functions.api]
  timeout = 26
